#!/bin/bash

# No args? -> exit
if [ $# -eq 0 ]; then
  echo "No arguments provided"
  exit 0
fi;
  
# Check if the project already
# exists
if [ -d "$1" ]; then
  echo "'$1' already exists."
  exit 1
fi;

PROJECT="$1"
MAKEFILE="$PROJECT/Makefile"
README="$PROJECT/README.md"
GITIGNORE="$PROJECT/.gitignore"

# Create the project
mkdir $PROJECT
touch $MAKEFILE
touch $README
touch $GITIGNORE

# Fill with the example config
echo "# $PROJECT" > $README
echo "SRCS=$PROJECT.c" > $MAKEFILE
cat "example/Makefile" >> $MAKEFILE
cat "example/example.c" > "$PROJECT/$PROJECT.c"
echo "*.o" > $GITIGNORE
echo "exec" >> $GITIGNORE
